
services:
  duckdb:
    container_name: duckdb
    build:
      context: .
    volumes:
      - ../mnt/tmp/04_iceberg/duckdb_data:/app/data
    stdin_open: true
    tty: true
    networks:
      - default
  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API port
      - "9001:9001"   # MinIO Console port
    environment:
      MINIO_ROOT_USER: minioadmin      
      MINIO_ROOT_PASSWORD: minioadmin  
    command: server /data --console-address ":9001"
    volumes:
      - ../mnt/tmp/04_iceberg/minio_data:/data
    networks:
      - default
  iceberg_rest:
    image: tabulario/iceberg-rest:1.6.0
    container_name: iceberg_rest
    ports:
      - "8181:8181"   # Iceberg REST API port
    environment:
      CATALOG_WAREHOUSE: s3://iceberg-catalog/warehouse
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
    depends_on:
      - minio
    networks:
      - default

networks:
  default:
    driver: bridge